package com.bifos.dooray.mcp.constants

object EnvVariableConst {

    val DOORAY_BASE_URL = "DOORAY_BASE_URL"
    val DOORAY_API_KEY = "DOORAY_API_KEY"
    val DOORAY_WEB_HOST = "DOORAY_WEB_HOST"
    val DOORAY_PRIORITY_PROJECT_CODES = "DOORAY_PRIORITY_PROJECT_CODES"
    val DOORAY_TEST_PROJECT_ID = "DOORAY_TEST_PROJECT_ID"
    val DOORAY_TEST_WIKI_ID = "DOORAY_TEST_WIKI_ID"
}
